import { UserAuthProvider } from '@/context/Context'
import './globals.css'
import { Work_Sans } from 'next/font/google'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserAuthProvider>
        <body className={inter.className}>
          <div className='flex flex-col justify-between h-[100%]'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </body>
      </UserAuthProvider>
    </html>
  )
}
